/*
 * This file has been automatically generated by cffi-grovel.
 * Do not edit it by hand.
 */

#include <errno.h>

#include <grovel/common.h>

int main(int argc, char**argv) {
  FILE *output = argc > 1 ? fopen(argv[1], "w") : stdout;
  fprintf(output, ";;;; This file has been automatically generated by "
                  "cffi-grovel.\n;;;; Do not edit it by hand.\n\n");

  /* constant section for EINTR */
#ifdef EINTR
  fprintf(output, "(cl:defconstant ");
  fprintf(output, "eintr");
  fprintf(output, " ");
  if(_64_BIT_VALUE_FITS_SIGNED_P(EINTR))
    fprintf(output, "%lli", (int64_t) EINTR);
  else
    fprintf(output, "%llu", (uint64_t) EINTR);
  fprintf(output, ")\n");
#else
  fprintf(output, "(cl:warn 'cffi-grovel:missing-definition :name 'EINTR)\n");
#endif

  if  (output != stdout)
    fclose(output);
  return 0;
}
